name: SandcastleHelpFileBuilder
on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs
jobs:
  build-docs:
    #runs-on: [self-hosted]
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install SHFB
      run: choco install sandcastle
    - name: Build
#      run: dotnet build --configuration Documentation --no-restore
      run: msbuild /p:Configuration=Documentation ./SystemToolsDocs/SystemT00lsDocs.shfbproj

