name: SandcastleHelpFileBuilder
on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs
jobs:
  build-docs:
    runs-on: [windows-latest]
    steps:
    - name: Notify of Build start
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORDBUILDSBOT }}
        status: ${{ job.status }}
        username: MzB Build Notifications
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Cache Sandcastle HelpFile Builder
      id: cache-shfb
      uses: actions/cache@v2
      env:
        cache-name: cache-shfb-nuget
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: ${{ runner.os }}-nuget-
    - name: Install SandcasteHelpFileBuilder via NuGet (if !cached)
      if: steps.cache-shfb.outputs.cache-hit != 'true'
      run: |
        cd SystemT00lsDocs
        dotnet add package EWSoftware.SHFB --version 2020.3.6
        cd ..
    - name: Build source to generate xml files
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Debug
        msbuild /p:Configuration=Documentation SystemT00ls-Full.sln
