name: SandcastleHelpFileBuilder
on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs
jobs:
  build-docs:
    runs-on: [windows-latest]
    steps:
    - name: Notify of Build start
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORDBUILDSBOT }}
        status: ${{ job.status }}
        username: MzB Build Notifications
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache Sandcastle HelpFile Builder
      id: cache-shfb
      uses: actions/cache@v2
      with:
        path: [ ${{ env.ChocolateyInstall }}\lib\sandcastle ]
        key: ${{ runner.os }}-shfb-choco
        restore-keys: ${{ runner.os }}-shfb-choco
    - name: Install SandcasteHelpFileBuilder via Chocolatey
      if: steps.cache-shfb.outputs.cache-hit != 'true'
      shell: powershell
      run: choco install sandcastle
    - name: Build
      run: msbuild /p:Configuration=Documentation

