name: SandcastleHelpFileBuilder
on:
  push:
    branches:
      - docs
  pull_request:
    branches:
      - docs
jobs:
  build-docs:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: dotnet restore
    - name: Build
#      run: dotnet build --configuration Documentation --no-restore
      run: E:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\MSBuild\\Current\\Bin\\MSBuild.exe /p:Configuration=Documentation ./SystemToolsDocs/SystemT00lsDocs.shfbproj

